# Generated by Django 5.2 on 2025-04-17 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(help_text='Ingrese 8 dígitos sin puntos ni guiones', max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
